headers:
  all:
    request:
      - propagate:
          named: 'Authorization'
      - propagate:
          named: 'User'
include_subgraph_errors:
  all: true # Propagate errors from all subgraphs
cors:
  origins:
    - http://localhost:3000 # Allows any locally-running client to run against your Router
    - https://studio.apollographql.com # Allows Apollo Studio to still run queries against your Router
authentication:
  jwt:
    jwks:
      - url: TODO: << add jwks url here >>
coprocessor:
  url: http://127.0.0.1:4041
  router:
    request:
      headers: true
      body: true
      context: true
      sdl: true
rhai:
  main: "require_jwt.rhai"
